name = "hossein-portfolio"
compatibility_date = "2025-09-25"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker/index.mjs"
assets = { directory = ".open-next/static", binding = "ASSETS" }
